### ISSUE TITLE
add CreateProductMetafield

### ISSUE THREAD

**Issue by choussamaster** [zf-fr/zfr-shopify#101]
Hi 
Can you add CreateProductMetafield method please?
[shopify-patch.txt](https://github.com/zf-fr/zfr-shopify/files/4127466/shopify-patch.txt)

**Comment by bakura10** [comment]
Hi,

This method is not needed. You can already add metafields to product using the CreateMetafield method.

**Comment by choussamaster** [comment]
the CreateMetafield add a global metafield
admin/api/{version}/metafields.json
the CreateProductMetafield add a metafield to a specific product
admin/api/{version}/products/{product_id}/metafields.json

**Comment by bakura10** [comment]
CreateMetafield can add a metafield to any resource by adding owner_resource and owner_id:

$client->createMetafield([
  'namespace' => 'foo',
  'key' => 'bar',
  'value_type' => 'string',
  'value' => 'hello',
  'owner_resource' => 'product',
  'owner_id' => PRODUCT_ID
]);
