### ISSUE TITLE
Blog Metafields Method missed

### ISSUE THREAD

**Issue by savchukoleksii** [zf-fr/zfr-shopify#102]
Today i found out that Blog also has metafields https://help.shopify.com/en/api/reference/metafield.
I will make PR when it will be done.

**Comment by bakura10** [comment]
You can already get and create blog metafields using the generic "Metafields" endpoint. Here is how you can create a blog metafield:

```php
$client->createMetafield([
  'namespace' => 'foo',
  'key' => 'bar',
  'value_type' => 'string',
  'value' => 'hello',
  'owner_resource' => 'blog',
  'owner_id' => BLOG_ID
]);
```
