### ISSUE TITLE
Add support for FulfillmentOrder

### ISSUE THREAD

**Issue by pittishgunner** [zf-fr/zfr-shopify#107]
Are yo uguys planning to add support for FulfillmentOrder ?
https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillmentorder

**Comment by bakura10** [comment]
I'm not doing back-end work anymore (I'm juts maintaining this library for the sake of the community). So while I won't personally add it, feel free to submit a pull request and I'll be happy to merge it!
