### ISSUE TITLE
Question: Retry Middleware

### ISSUE THREAD

**Issue by savchukoleksii** [zf-fr/zfr-shopify#114]
Is it possible to add a custom Retry Middleware?
For example, I want to throw an exception with retry data in queue worker to release job back into the queue. Current solution just sleeps until the next request.
@bakura10

**Comment by ryanadair** [comment]
@savchukoleksii 

Few ideas:

* You can extend ShopifyClient and overwrite ```createDefaultClient()``` in order to set your own middleware.
* You can create your own GuzzleClient and pass it into the ShopifyClient's constructor. This new GuzzleClient can have whatever middleware you would need.
