### ISSUE TITLE
Retry

### ISSUE THREAD

**Issue by danizord** [zf-fr/zfr-shopify#12]
@bakura10 Given that sometimes we may reach Shopify API limit, what about having an auto-retry middleware?

**Comment by bakura10** [comment]
Yeah. Should be a good idea. I think that guzzle already has built in primitices for that (however be sure to check the Guzzle3 documentation as this sdk does not use v6 yet)

**Comment by danizord** [comment]
Fixed by https://github.com/zf-fr/zfr-shopify/pull/25
