### ISSUE TITLE
Need this package in PHP version 8

### ISSUE THREAD

**Issue by efficientbit** [zf-fr/zfr-shopify#120]
Hi @bakura10 

Can you please add support for PHP version 8 as well? We just installed in Laravel (PHP Framework) version 8 and we are getting the following error in the composer output.

[InvalidArgumentException]                                                                                              
  Package zfr/zfr-shopify has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version:  
    - zfr/zfr-shopify 6.6.1 requires php ~7.0 which does not match your installed version 8.0.1.

**Comment by bakura10** [comment]
Hi,

You can submit a PR, I will be happy to merge it with the change :) (I am no longer doing back-end work so I am now relying only on user PR for changes).

Thanks!

**Comment by ryanadair** [comment]
Submitted PR #122 to address this, also brings up unit tests to latest supportable version of PHPUnit, tests pass also.

@bakura10

**Comment by bakura10** [comment]
Fixed by #122
