### ISSUE TITLE
Provide config

### ISSUE THREAD

**Issue by bakura10** [zf-fr/zfr-shopify#2]
@danizord, when do you think you will be able to release your Expressive config merger? So we could provide some default config on such libraries.

**Comment by danizord** [comment]
@bakura10 seems like Zend\Expressive already found a way to build modular applications: http://zend-expressive.readthedocs.org/en/latest/cookbook/modular-layout/ so I'm not sure if I should release that one after all.

**Comment by bakura10** [comment]
It does not seem as transparent as your solution. You have to add a class per "module" (which introduces again the issue of adding framework specific classes to generic libraries), and you have to explicitly add each library.

Your solution seemed more transparent: just add composer extra and boom were done.  We don't even need of setting caching as it would be aggregated by Composer directly.

Or did I misunderstood this feature?

Envoyé de mon iPhone

**Comment by bakura10** [comment]
Obviously there are still some advantages like being able to control the order of merging. Mmmhh.

Envoyé de mon iPhone

**Comment by bakura10** [comment]
Also, the issue I'm seeing is that it's not really transitive. For instance if we have a module "Common" that uses "ZfrShopify" internally, we'll need to make sure to add the "ZfrShopify" module to the list, as well as any other dependencies that ZfrShopify may have too, hence forcing to scan dependencies of dependencies and add all of them to the list.

With your system, from what I understand this is completely automatic.

**Comment by danizord** [comment]
>We don't even need of setting caching as it would be aggregated by Composer directly.

Yep

>Obviously there are still some advantages like being able to control the order of merging. Mmmhh.

You can have some control by chaging the order in `require` section of `composer.json`

>For instance if we have a module "Common" that uses "ZfrShopify" internally, we'll need to make sure to add the "ZfrShopify" module to the list, as well as any other dependencies that ZfrShopify may have too, hence forcing to scan dependencies of dependencies and add all of them to the list.
>
>With your system, from what I understand this is completely automatic.

Yep.

**Comment by bakura10** [comment]
So your system sounds superior to me?

**Comment by danizord** [comment]
Except for the low control of merging order (you can control the order of your direct dependencies but can't control the order of dependencies of dependencies), yes, it looks better, may I give it a try?
