### ISSUE TITLE
No way to get status code from response?

### ISSUE THREAD

**Issue by roberttolton** [zf-fr/zfr-shopify#37]
From what I can tell, there isn't a way to get the status code from the response?

```
$response = $shopifyClient->createProduct($product);
```

Would return the response JSON from Shopify, so is the only way to do error handling / checking to check what properties / keys / values are returned?

**Comment by bakura10** [comment]
Hi :),

When everything is successful, ZfrShopify will always returns the payload directly, not a response. Also to make it easier to use, we directly remove the top key that Shopify add. So basically:

```php
$product = $shopifyClient->createProduct(...);

// You can use directly $product['title'] for instance
```

Regarding error, you must use exceptions. You can catch any error by catching the CommandException:

```php
use GuzzleHttp\Command\Exception\CommandException;

try {
  $product = $shopifyClient->createProduct($product);
} catch (CommandException $exception) {
  $response = $exception->getResponse();
  // You can also get the original request: $request = $exception->getRequest()
}
```

This will watch both 4xx and 5xx error. You can be a bit more granular by catching CommandClientException instead (only 4xx) or ServerClientException (only 5xx).

I will try to add this to the doc :).

I'm closing that for now but if you have any other question, feel free to ask!
