### ISSUE TITLE
Method createDefaultClient() always appends a .myshopify.com to the shop url which is a problem for a custom shop domain

### ISSUE THREAD

**Issue by jschaedl** [zf-fr/zfr-shopify#42]
We are using a custom domain name for our Shopify shop and having problems accessing it via the ShopifyClient. The method `createDefaultClient()` always appends a *.myshopify.com* to the shop url.

https://github.com/zf-fr/zfr-shopify/blob/2.1.2/src/ShopifyClient.php#L426

which is a problem if you use custom domains.

**Comment by bakura10** [comment]
What kind of error are you experiencing? The myshopify.com are the canonical address of each Shopify store, and the one that is guaranted to never change. Even Shopify recommend to always use the .myshopify.com address when hitting the API.

**Comment by jschaedl** [comment]
We are using a configured application proxy and tried to call the shopify api using this proxy url. It is supported on shopify's side: https://help.shopify.com/api/tutorials/application-proxies#proxy-request

So I think using a proxy url should be supported :-)

**Comment by bakura10** [comment]
Even for proxy application, Shopify always send you the the shop domain: GET/proxy/extra/path/components?extra=1&extra=2&shop=shop-name.myshopify.com&path_prefix=%2Fapps%2Fawesome_reviews&timestamp=1317327555&signature=a9718877bea71c2484f91608a7eaea1532bdf71f5c56825065fa4ccabe549ef3 

I don't want I think I want to support this feature to be honest. Custom domain are subject to change, and you cannot reliably know all the possible URLs (the merchant can have many different sub-domains based on the language).

The only reliable way to interact with the Shopify API in a non breaking way is through the myshopify domain whihc is immutable and is passed in all authentication stage by Shopify.

**Comment by jschaedl** [comment]
Ok, I see. Thanks for your patience :-)

**Comment by bakura10** [comment]
You're welcome. If you stumble into a use case that absolutely need a real domain (but I honestly don't see any), do not hesitate to re-open this issue and I'll be happy to re-consider.
