### ISSUE TITLE
GetMetafields not working with metafield[owner_id] and metafield[owner_resource]

### ISSUE THREAD

**Issue by jschaedl** [zf-fr/zfr-shopify#56]
Hi,

we are using your library for some time now and it's really awesome. There is only one thing we have experienced lately:
We have a problem getting metafields using `owner_id` and `owner_resource`. We followed the shopify documentation https://help.shopify.com/api/reference/metafield#index and used the GetMetafields command as follows:

```
...
$this->shopifyClient = new ShopifyClient([
    'private_app' => true,
    'api_key'     => $apiKey,
    'password'    => $password,
    'shop'        => $storeUrl
]);
...

$metafields = $this->shopifyClient->getMetafields([
    'metafield[owner_id]' => $shopifyProductId,
    'metafield[owner_resource]' => 'product'
]);
```

Unfortunately the returned metafields array is always empty. When we call this endpoint with the same query params via postman, a proper metafields list is returned. 

So we debugged it and found out that guzzle don't append the query params to the uri. The uri should actually look like: [https://your-shopify-url/admin/metafields.json?metafield[owner_id]=10251204676&metafield[owner_resource]=product](https://your-shopify-url/admin/metafields.json?metafield[owner_id]=10251204676&metafield[owner_resource]=product) 

With this in mind we checked the guzzle service configuration for this endpoint and saw that it defines the metafields parameter as an object: https://github.com/zf-fr/zfr-shopify/blob/master/src/ServiceDescription/Shopify-v1.php#L1922

So our question is: How should the criteria array look like to get the metafields? We've already tried the following variants, but none of them worked:

```
$criteria = [
    'metafield[owner_id]' => $shopifyProductId,
    'metafield[owner_resource]' => 'product'
];

$criteria = [
    'metafield => [
        'owner_id' => $shopifyProductId,
        'owner_resource' => 'product'
    ]
];

```
Would be great if you could give us a hint. :-) Thanks a lot!

**Comment by bakura10** [comment]
Hi,

Thanks for your kind words regarding the library!

We're using that extensively and here is what we do:

```php
$shopifyClient->getMetafields([
  'metafield' => [
    'owner_id' => $productId,
    'owner_resource' => 'product'
  ]
]);
```

This has always worked correctly for us so it's a bit strange. Which version of the library are you using?

**Comment by jschaedl** [comment]
Thanks for the quick answer :-)
We are using v2.1.

**Comment by jschaedl** [comment]
Unfortunately 

```
$shopifyClient->getMetafields([
  'metafield' => [
    'owner_id' => $productId,
    'owner_resource' => 'product'
  ]
]);
```
is not working for us :-( The query params are not appended.

Here is a dump of the $criteria array:

```
array:2 [
  "metafield" => array:2 [
    "owner_id" => 10251204676
    "owner_resource" => "product"
  ]
]
```

and here the dump of the uri:

```
Uri {#2368 
  -scheme: ""
  -userInfo: ""
  -host: ""
  -port: null
  -path: "admin/metafields.json"
  -query: ""
  -fragment: ""
}
```

**Comment by bakura10** [comment]
What the hell. @danizord ?

**Comment by bakura10** [comment]
That's super strange. Could you please try to update to the very last version (2.2 somethin)g ?

**Comment by bakura10** [comment]
Can you make sure you do not have an hardcoded version of guzzle services in your composer.json?

**Comment by jschaedl** [comment]
I updated to the latest version and now the query params were appended but the uri looks like this now:

http://shopifyurl/admin/metafields.json?metafield=10251204676&metafield=product

it results in a 400 Bad Request :-(

**Comment by bakura10** [comment]
Meh ôÔ... I can see some changes in guzzle-services: https://github.com/guzzle/guzzle-services/releases

I can see that on our end we're using v1.1.0. Can you set a fixed dependency to Guzzle services to 1.1.0 ?

**Comment by danizord** [comment]
@jschaedl can you please share your composer.lock? At least the Guzzle/ZfrShopify related parts.

**Comment by jschaedl** [comment]
Hi @danizord 

here are the Guzzle/ZfrShopify related parts from our composer.lock

```
{
            "name": "zfr/zfr-shopify",
            "version": "2.2.9",
            "source": {
                "type": "git",
                "url": "https://github.com/zf-fr/zfr-shopify.git",
                "reference": "e5cae3072237b7fccd48d87a4c4e9733ca369fdd"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/zf-fr/zfr-shopify/zipball/e5cae3072237b7fccd48d87a4c4e9733ca369fdd",
                "reference": "e5cae3072237b7fccd48d87a4c4e9733ca369fdd",
                "shasum": ""
            },
            "require": {
                "container-interop/container-interop": "^1.1",
                "guzzlehttp/guzzle-services": "^1.0",
                "php": "~7.0",
                "psr/http-message": "^1.0",
                "zendframework/zend-diactoros": "^1.3"
            },
            "require-dev": {
                "phpunit/phpunit": "^5.2",
                "squizlabs/php_codesniffer": "^2.5",
                "zendframework/zend-servicemanager": "^3.0"
            },
            "suggest": {
                "zendframework/zend-servicemanager": "^3.0"
            },
            "type": "library",
            "extra": {
                "zf": {
                    "config-provider": [
                        "ZfrShopify\\ConfigProvider"
                    ]
                }
            },
            "autoload": {
                "psr-4": {
                    "ZfrShopify\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Michaël Gallego",
                    "email": "mic.gallego@gmail.com",
                    "homepage": "http://www.michaelgallego.fr"
                }
            ],
            "description": "PHP library for interacting with the Shopify REST API",
            "homepage": "https://github.com/zf-fr/zfr-shopify",
            "keywords": [
                "api",
                "shopify"
            ],
            "time": "2017-05-24T17:22:03+00:00"
        }
```

**Comment by jschaedl** [comment]
Yeah. Updating guzzlehttp/guzzle-services to version 1.1.0 helped!

Thank you very much guys. You helped me a lot! :-)

**Comment by bakura10** [comment]
Damn, so this means there is a major BC in guzzle-services...

**Comment by bakura10** [comment]
@jschaedl , we're working with @danizord on a new version of ZfrShopify (I've just merged a pending PR to master). This new version simplifies drastically the descriptor by removing all optional parameters.

Before, we use to explicitly specify ALL parameters one by one. Not only it took us a lot of time to maintain it (and led to a lot of lost time... where we used a parameter to realized it was not sent because absent from the descriptor).

We therefore loose a bit of validation but easier maintenance and extensibility.

In this new version, I've tried your use case with the very last version of Guzzle and it works. Could you please therefore, out of curiosity, to try to use the master branch of ZfrShopify, remove the fixed dependency to Guzzle Services (so the very last version is pulled) and let me know if it works?

Just try this locally though or on a dev branch, we haven't tag anything yet and we'll do some more testing internally, but that should improve things.

**Comment by bakura10** [comment]
Hey !

Just to let you know that we've released v3 of ZfrShopify. Normally this should work better. Do  not hesitate to try it and let us know :).

**Comment by bakura10** [comment]
In the meantime, I'm closing this issue :).

**Comment by jschaedl** [comment]
@romanowskip FYI
