### ISSUE TITLE
getGiftCardsIterator and getGiftCards issues

### ISSUE THREAD

**Issue by webharvesting** [zf-fr/zfr-shopify#57]
Hello,

I think there are same problems with the two methods above as Shopify API /admin/gift_cards.json doesn't recognize the since_id (see $args of iterateResources in ShopifyClient.php) and the method definition in Shopify-v1.php should look like:

GetGiftCards' => [
            'httpMethod'           => 'GET',
            'uri'                  => 'admin/gift_cards.json',
            'responseModel'        => 'GenericModel',
            'summary'              => 'Receive a list of all Gift Cards',
            'data'                 => ['root_key' => 'gift_cards'],
            'status' => [
                'description' => 'URL of the script tag',
                'location'    => 'json',
                'type'        => 'string'
            ],
            'page' => [
                'description' => 'Page to show',
                'location'    => 'query',
                'type'        => 'integer',
                'required'    => false,
            ],
            'limit' => [
                'description' => 'Amount of results',
                'location'    => 'query',
                'type'        => 'integer',
                'min'         => 1,
                'max'         => 250,
                'required'    => false,
            ],
            'additionalParameters' => [
                'location' => 'query',
            ]

**Comment by bakura10** [comment]
Hi,

That's strange, I'm pretty sure it's an error on their documentation. However, in the mean time could you maybe upgrade to the v3 or ZfrShopify?

Normally it should be backward compatible, and in this release we have actually removed all the non-required parameters and instead use the additionalParameters array descriptor: https://github.com/zf-fr/zfr-shopify/blob/master/src/ServiceDescription/Shopify-v1.php#L803

In the past we used to explicitly list all arguments but this caused a lot of issues as we had to update the library whenever Shopify added a new parameter, and we also forgot a lot (which caused a lot of hard to debug issue, because those parmaeters were not passed).

In the V3 we only list required parameters, but all optional parameters (like limit, page...) are usable directly with the additionalParameters. This therefore largely reduce the maintenance on our part :).

I'm closing that for now but if I misunderstood your question do not hesitate!

**Comment by webharvesting** [comment]
Hi Bakura,

this is not a question, but it wanted to be a contribution to your valuable library, I have already override your code and made it functional on my project. With regard to V3, V1 is the version Composer downloads on Symfony 3.2 following your docs.

**Comment by bakura10** [comment]
What do you mean by downloading the v1 ? https://github.com/zf-fr/zfr-shopify#installation

Actually I tihnk the confusion comes from the descriptor which is called Shopify-v1 and the library version whihc is v3 :p.

**Comment by webharvesting** [comment]
Ah OK therefore I think I am updated.

So if you hack your iterator (I understand this can not be the definitive solution, it is just an example to explain the issue) as for the code below and update Shopify-v1 getGiftCards as for a above, getGiftCardsIterator works properly. At the moment  $args['since_id'] = end($results)['id']; causes the method to return always the same results while you need to move forward with $args['page'] ++; .

Maybe I am wrong or I don't know how to call the getGiftCardsIterator, if you think this is the case, please tell me how to call getGiftCardsIterator properly.

private function iterateResources(string $commandName, array $args): Generator
    {
        // When using the iterator, we force the maximum number of items per page. Also, if no "since_id" is set, we force it to 0 because by
        // default Shopify sort resources by title
        $args['limit']    = 250;
        if($commandName == 'getGiftCards')
            $args['page'] = $args['page'] ?? 1;
        else
            $args['since_id'] = $args['since_id'] ?? 0;

        // Because the iteration depends on the presence of the "id" field, we must make sure that if the "fields" filter is set, it contains
        // at the minimum the "id" one. We make a simple detection here
        if (isset($args['fields'])) {
            $fields         = explode(',', str_replace(' ', '', $args['fields']));
            $args['fields'] = implode(',', array_unique(array_merge(['id'], $fields)));
        }

        do {
            $command = $this->getCommand($commandName, $args);
            $results = $this->execute($command);

            foreach ($results as $result) {
                yield $result;
            }

            if($commandName == 'getGiftCards')
                $args['page'] ++;
            else
                // Advance the since_id
                $args['since_id'] = end($results)['id'];
        } while(count($results) >= 250);
    }

**Comment by bakura10** [comment]
Hi !

I think I got it. While I'd like to avoid different ways of doing iteration (especially since cursor based iteration using since_id has some advantages), I think your fix make sense. Could you open a PR ? :)

I'm also going to contact Shopify to ask them why this is not available.

**Comment by webharvesting** [comment]
Could you open a PR ? Does it mean Pull Request ? Yes sure, following git hub doc looks like I need to create a branch for that, the branch is ready in my local but I cannot push it. Git Hub says: remote: Permission to zf-fr/zfr-shopify.git denied to webharvesting. Please advice

**Comment by bakura10** [comment]
Never mind, I've did a PR in #58. Can you please try the code and make sure that it works properly for you? :) If that works I'll merge the PR.

**Comment by webharvesting** [comment]
Tested and worked for me !
