### ISSUE TITLE
Missing count methods

### ISSUE THREAD

**Issue by tseven** [zf-fr/zfr-shopify#60]
I just took this library for a spin and it looks really good. Thanks for creating this!

I noticed none of the shopify count methods are defined.

i.e.
>/admin/products/count.json
>/admin/customers/count.json

Thanks again for this library :)

**Comment by bakura10** [comment]
Hi @tseven ,

Thanks a lot for the feedback. I've made a PR (#61) that adds all those endpoints :).

I'm waiting for some feedback from @danizord and will merge next week !

**Comment by bakura10** [comment]
I've just tagged version 3.2.0 @tseven which contains this :).

**Comment by tseven** [comment]
@bakura10 That's great, thanks!
