### ISSUE TITLE
How do you update nested resources?

### ISSUE THREAD

**Issue by greatwitenorth** [zf-fr/zfr-shopify#62]
I'm trying to figure out how to update nested resources. For example, a customer's address. Can you provide an example of how I'd update a customer's address given the customer ID and address ID?

**Comment by greatwitenorth** [comment]
I did find a way to do this which requires modifying Shopify-v1.php:

```
'UpdateCustomerAddress' => [
            'httpMethod'    => 'PUT',
            'uri'           => 'admin/customers/{customer_id}/addresses/{id}.json',
            'responseModel' => 'GenericModel',
            'summary'       => 'Modify a customer\'s address',
            'data'          => ['root_key' => 'customer_address'],
            'parameters'    => [
                'id' => [
                    'description' => 'Address ID',
                    'location'    => 'uri',
                    'type'        => 'integer',
                    'required'    => true,
                ],
                'customer_id' => [
                    'description' => 'Customer ID',
                    'location'    => 'uri',
                    'type'        => 'integer',
                    'required'    => true,
                ],
            ],
            'additionalParameters' => [
                'location' => 'json',
            ],
        ],
```

Obviously it'd be good to add the other methods as well for a customer's address.

**Comment by bakura10** [comment]
Hi,

Yes, we are indeed currently implemented a limited subset of resources. You can see the list here: https://github.com/zf-fr/zfr-shopify#implemented-endpoints

Feel free to implement additional endpoints in a PR (if you do, make sure to include ALL possible requests so create/update/delete/count...).
