### ISSUE TITLE
Ability to set Guzzle connect_timeout?

### ISSUE THREAD

**Issue by tseven** [zf-fr/zfr-shopify#67]
I simulated a network issue between my server and Shopify with a firewall rule and the requests hang with a really long timeout (possibly defaulting to php's exec timeout).

Is it possible pass a connect_timeout value to all guzzle connections that zfr-shopify makes?

Thanks

**Comment by danizord** [comment]
Yeah, you can instantiate `ShopifyClient` passing a custom instance of `GuzzleHttp\Client` configured with `connect_timeout` :)

**Comment by bakura10** [comment]
I'm closing this issue as this seems to answer the question :).

**Comment by tahafarooqui** [comment]
What is default connect_timeout ?
