### ISSUE TITLE
How to get analytics reports?

### ISSUE THREAD

**Issue by llxx-lord-xxll** [zf-fr/zfr-shopify#81]
I couldn't figure out how to get analytics reports from ZFR Shopify.

I am now trying with GraphQL, but is there any way to execute shopify_ql to get reports and other custom commands ?

I saw execute function to execute commands, but i am new to this library, so i really need your help!

**Comment by bakura10** [comment]
Hi !

ShopifyQL is not something that can be done in API nor GraphQL. ShopifyQL is an API that can only be used in embedded apps, in JavaScript, as indicated in the documentation: https://help.shopify.com/en/api/reference/analytics/shopify-ql

This is therefore outside the scope of this package, which only deal with REST API and GraphQL API.
