### ISSUE TITLE
createProductImage and JSON encoding

### ISSUE THREAD

**Issue by thickey256** [zf-fr/zfr-shopify#84]
I had a couple of problem with createProductImage yesterday, I think it is down to how Guzzlehttp is encoding the JSON.

When sending the data to create a new image [Docs here](https://help.shopify.com/en/api/reference/products/product-image#create) I want to pass it a very simple array with the url for the image.
```{
  "image": {
    "src": "http://example.com/rails_logo.gif"
  }
}
```
I was getting every post rejected by the Shopify API saying that it can't find the image.  After doing some var_dumping of the Shopify.php class it looks like it was adding extra slashes to the URL [basic example here](https://3v4l.org/l5eju).

In the end my solution was to make my own Guzzle object and use that, but this sort of goes against the whole point of using zfr-shopify 😁 

My code ended up looking like this
```
$image_info['image']['src'] = 'http://example.com/rails_logo.gif';
$image_json = json_encode($image_info,JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);

$product_id = '123456789';
$shopifyClient = new \GuzzleHttp\Client();
$uri = 'https://'.getenv('SHOPIFY_API_SHOP').'/admin/products/'.$product_id.'/images.json';
try{
	$response = $shopifyClient->post($uri, [
	'auth' => [
			getenv('SHOPIFY_API_KEY'),
			getenv('SHOPIFY_API_PASSWORD')
		],
		'body' => $image_json,
		'headers' => ['Content-Type' => 'application/json']
	]);
}
catch (\GuzzleHttp\Exception\ClientException $e)
{
	$response = $e->getResponse();
	$responseBodyAsString = $response->getBody()->getContents();
	return json_decode($responseBodyAsString);
}

$new_image =  \GuzzleHttp\json_decode($response->getBody());
return $new_image;
```
I think/assume that it will be the same deal if you add the base64 encoded data of an image as an attachment as this also has slashes in it.

Another major problem I had was Shopify needs to have the content-type header set correctly for the source image.  My images are on an S3 bucket and I forgot to change these from the default. But that's my fault.

**Comment by bakura10** [comment]
Hi !

ZfrShopify removes the need for you to set up the initial top key. So you should use the following code instead:

```php
$shopifyClient->createProductImage([
  'product_id' => 'YOUR ID',
  'src' => 'YOUR SRC'
]);
```

This should solve the issue, but if this still does not work let me know and I'll re-open the issue ;).

**Comment by thickey256** [comment]
Yes, now you say this it makes total sense... and works!  Not going to make that mistake again, Thanks for the help
