### ISSUE TITLE
getOrders returns only last 60 days despite having the read_all_orders permission

### ISSUE THREAD

**Issue by toojazzy** [zf-fr/zfr-shopify#94]
Just as the title says, we got the permission already and it is correctly reported by getAccessScopes, get getOrders (and getOrderCount) doesn't see anything beyond the normal limit. Is there a work around this issue? I already tried creating own access token but it proven to be too complicated without any documentation on the topic. Thanks!

**Comment by bakura10** [comment]
Hi,

This is something you will need to check with Shopify. The sdk just interact with the endpoints of Shopify. If not all orders are returned for your given token you’ll need to check with them as for why.
